### Upload a file
POST http://localhost:3000/api/files/upload
Content-Type: multipart/form-data; boundary=----MyBoundary123

------MyBoundary123
Content-Disposition: form-data; name="file"; filename="hello.txt"
Content-Type: text/plain

Hello! This is a test file.
------MyBoundary123--
